version: '2.2'
services:
  lab:
    image: cnsoist/steps:5.0.2
    build: recipe
    hostname: $HOST
    ports:
    - "8888:8888"
    env_file: .env
    entrypoint: [/usr/bin/entrypoint]
    command:
    - jupyter
    - lab
    - --no-browser
    - --allow-root
    - --ip=0.0.0.0
    - --notebook-dir=/opt/src/notebooks
    volumes:
    - $PWD/notebooks:/opt/src/notebooks
    scale: 1
