version: '2.2'
services:
  steps:
    image: cnsoist/steps-testing:3.1
    build: recipe
    hostname: $HOST
    ports:
    - "8888:8888"
    environment:
    - USER_LOGIN=$USER
    - USER_ID=$DUID
    - GROUP_ID=$DGID
    volumes:
    - $SSH_AUTH_SOCK:/ssh_agent
    - $PWD/notebooks:/opt/src/notebooks
