version: '2.2'
services:
  jupyterlab:
    image: cnsoist/steps-testing:3.1
    build: recipe
    hostname: $HOSTNAME
    ports:
    - "8888:8888"
    environment:
    - SSH_AUTH_SOCK=/ssh_agent
    - USER_LOGIN=$USER
    - USER_ID=$UID
    - GROUP_ID=$GID
    volumes:
    - $SSH_AUTH_SOCK:/ssh_agent
    - $PWD/notebooks:/opt/src/notebooks
