version: '2.2'
services:
  lab:
    image: cnsoist/steps:3.2
    build: recipe
    hostname: $HOST
    ports:
    - "8888:8888"
    environment:
    - USER_LOGIN=$USER
    - USER_ID=$DUID
    - GROUP_ID=$DGID
    volumes:
    - $PWD/notebooks:/opt/src/notebooks
  notebook:
    extends: lab
    command:
        - jupyter
        - notebook
        - --notebook-dir=/opt/src/notebooks
        - --ip=0.0.0.0
        - --no-browser
        - --allow-root
