version: '2.2'
services:
  lab:
    image: cnsoist/steps:3.6
    build: recipe
    hostname: $HOST
    ports:
    - "8888:8888"
    environment:
    - USER_LOGIN=$USER
    - USER_ID=$DUID
    - GROUP_ID=$DGID
    entrypoint: [/usr/bin/entrypoint]
    command:
    - jupyter
    - lab
    - --no-browser
    - --allow-root
    - --ip=0.0.0.0
    - --notebook-dir=/opt/src/notebooks
    volumes:
    - $PWD/notebooks:/opt/src/notebooks
  notebook:
    extends: lab
    command:
    - jupyter
    - notebook
    - --no-browser
    - --allow-root
    - --ip=0.0.0.0
    - --notebook-dir=/opt/src/notebooks
